version: '3.9'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - "../initdb:/docker-entrypoint-initdb.d"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${POSTGRES_MEM_LIMIT}
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: db-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    links:
      - postgres:pgsql-server

volumes:
  db:
    driver: local
  pgadmin:
    driver: local