### Customer Service API
POST localhost:8080/blank
Content-Type: application/json

{
  "id": "{{$random.uuid}}"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 202, "Response status is not 202");
        client.assert(response.body["message"] === "Blank saved successfully!", "Response message is not valid");
    });
%}
