blanksystem:
  blank:
    service:
      image:
        name: com.blanksystem/blank-service
        version: 1.0.0-alpha

    events:
      journal:
        blank:
          topic: blank.1.0.event.created
          consumer:
            group: blank-topic-consumer
spring:
  datasource:
    url: jdbc
kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url: http://localhost:8081

third:
  basic:
    auth:
      username: admin
      password: pass
  jsonplaceholder:
    url: https://jsonplaceholder.typicode.com
    basic:
      auth:
        username: admin
        password: pass