openapi: 3.1.0
info:
  title: Blank OpenAPI
  description: |-
    This is a Blank Server based on the OpenAPI 3.1 specification.

    Some useful links:
    - [The Blank repository](https://github.com/lg-labs/blank-service)
    - [The source API definition for the Blank](https://github.com/lg-labs/blank-service/tree/main/blank-api/src/main/resources/spec/openapi.yaml)

  termsOfService: https://github.com/lg-labs/blank-service
  contact:
    email: 105936384+lglabs@users.noreply.github.com
  license:
    name: MIT License
    url: https://github.com/lg-labs/blank-service/tree/main/LICENSE
  version: v3.0
externalDocs:
  description: Find out more about Blank System
  url: https://lg-labs.github.io/blank-service/
servers:
  - url: http://localhost:8181
tags:
  - name: blank
    description: Operations about blank
    externalDocs:
      description: Find out more about our blank system
      url: https://lg-labs.github.io/blank-service/
paths:
  /blank:
    post:
      tags:
        - blank
      summary: Add a new blank to the blank system
      description: Add a new blank to the blank system
      operationId: addBlank
      requestBody:
        $ref: '#/components/requestBodies/Blank'
      responses:
        '202':
          description: Accepted
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - blank_auth:
            - write:blank
components:
  schemas:
    Blank:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
          examples: [ username ]
        firstName:
          type: string
          examples: [ firstName ]
        lastName:
          type: string
          examples: [ lastName ]

  requestBodies:
    Blank:
      description: Blank object that needs to be added to the blank system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Blank'
          examples:
            customer1:
              $ref: '#/components/examples/blank1'
            customer2:
              $ref: '#/components/examples/blank2'

  examples:
    blank1:
      summary: An example of a Blank 1
      value:
        id: d215b5f8-0249-4dc5-89a3-51fd148cfb41
        username: blank1
        firstName: blank1
        lastName: blank1
    blank2:
      summary: An example of a Blank 2
      value:
        id: d215b5f8-0249-4dc5-89a3-51fd148cfb42
        username: blank2
        firstName: blank2
        lastName: blank2

  securitySchemes:
    blank_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://lg-labs.github.io/blank-service/
          scopes:
            write:blank: add blank in your system
    api_key:
      type: apiKey
      name: api_key
      in: header
