info:
  app:
    name: ${spring.application.name}
    version: "@project.version@"
server:
  port: 8080



blanksystem:
  blank:
    events:
      journal:
        blank:
          topic: blank.1.0.event.created
          consumer:
            group: blank-topic-consumer

spring:
  application:
    name: blank-service
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres?currentSchema=blank&binaryTransfer=true&reWriteBatchedInserts=true
    username: sa
    password: sa

  liquibase:
    liquibase-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sleuth:
    sampler:
      probability: 1.0

third:
  basic:
    auth:
      username: admin
      password: admin
  jsonplaceholder:
    url: localhost:7070
    basic:
      auth:
        username: admin
        password: pass
feign:
  client:
    config:
      jsonplaceholder:
        url: ${third.jsonplaceholder.url}
      default:
        loggerLevel: FULL

log:
  path: ./logs
