name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      - name: Configure Maven settings.xml
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PKG_GITHUB_TOKEN }} # o usa otro token si es necesario
        run: |
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                    http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                  <server>
                      <id>github</id>
                      <username>${GITHUB_USERNAME}</username>
                      <password>${GITHUB_TOKEN}</password>
                  </server>
              </servers>
              <profiles>
                  <profile>
                      <id>github</id>
                      <repositories>
                          <repository>
                              <id>github</id>
                              <url>https://maven.pkg.github.com/lg-labs-pentagon/*</url>
                              <snapshots>
                                <enabled>true</enabled>
                              </snapshots>
                          </repository>
                      </repositories>
                  </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>github</activeProfile>
              </activeProfiles>
          </settings>
          EOF
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: mvn -B verify

      - name: Check if PNG exists
        run: |
          if [ ! -f ./target/dependency-graph.png ]; then
            echo "File not found!"
            exit 1
          fi

      - name: Cache generated PNG
        uses: actions/cache@v4.0.2
        with:
          path: ./target/dependency-graph.png
          key: ${{ runner.os }}-png-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-png-cache-
      - name: Move PNG to destination folder
        run: cp ./target/dependency-graph.png ./blank-report/app/docs/img/
