name: Continuous Deployment

on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed
    conclusions:
      - success
permissions:
  contents: write

jobs:
  ghpage:
    name: GitHub Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download MkDocs
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: mkdocs
          path: ./site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
  site:
    name: Web Site
    runs-on: ubuntu-latest
    steps:
      - name: Download firebase.json
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: firebase-json
          path: ./

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: openapi-doc
          path: ./openapi

      - name: Download AsyncAPI artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: asyncapi-doc
          path: ./asyncapi

      - name: Download Test reports
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: test-reports
          path: ./reports

      - name: Download Cucumber Report
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: cucumber-report
          path: ./atdd

      - name: Download Site artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: mkdocs
          path: ./docs
      - name: Display structure of downloaded files
        run: ls -R
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLANK_SERVICE_ATDD }}
          channelId: live
          projectId: blank-service-atdd
          entryPoint: .
