name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
permissions:
  contents: write
jobs:
  page:
    name: Gh Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x
      - uses: actions/cache@v4.0.2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - name: Download MkDocs
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: mkdocs
          path: ./pages
      - run: ls -la ./pages
      - run: cd pages && mkdocs gh-deploy --force
      - name: Upload Site artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-site
          path: ./pages/site
  site:
    name: Web Site
    runs-on: ubuntu-latest
    needs: page
    steps:
      - name: Download firebase.json
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: firebase-json
          path: ./

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: openapi-doc
          path: ./openapi

      - name: Download AsyncAPI artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: asyncapi-doc
          path: ./asyncapi

      - name: Download Test reports
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: test-reports
          path: ./reports

      - name: Download Cucumber Report
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: cucumber-report
          path: ./atdd
      - name: Download Site artifact
        uses: actions/download-artifact@v4
        with:
          name: main-site
          path: ./docs
      - name: Display structure of downloaded files
        run: ls -R
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLANK_SERVICE_ATDD }}
          channelId: live
          projectId: blank-service-atdd
          entryPoint: .
