name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Restore PNG from cache
        uses: actions/cache@v4.0.2
        with:
          path: ./target/dependency-graph.png
          key: ${{ runner.os }}-png-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-png-cache-
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x
      - uses: actions/cache@v4.0.2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: cp ./target/dependency-graph.png ./blank-report/app/docs/img/
      - run: cd blank-report/app && mkdocs gh-deploy --force